// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollectionHighlightController from "./collection_highlight_controller"
application.register("collection-highlight", CollectionHighlightController)

import CommentInteractivityController from "./comment_interactivity_controller"
application.register("comment-interactivity", CommentInteractivityController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModelsFilterController from "./models_filter_controller"
application.register("models-filter", ModelsFilterController)

import NavbarSearchController from "./navbar_search_controller"
application.register("navbar-search", NavbarSearchController)

import TinymceController from "./tinymce_controller"
application.register("tinymce", TinymceController)
