production:
  periodic_unatached_uploads:
    class: Maintenance::CleanupUnatachedUploadsJob
    schedule: every day at 03:00 am
# development:
#   periodic_unatached_uploads:
#     class: Maintenance::CleanupUnatachedUploadsJob
#     schedule: every day at 03:00 am