default: &default
# Use an impossible selector because the gem demands one.
# I will manually select which forms get tinymce with TinyMCERails.initialize
  selector: '*:not(*)'
  toolbar:
    - undo redo | bold italic underline | bullist numlist
  plugins:
    - lists
  block_formats: 'Paragraph=p'
  hidden_input: false
  inline: true
  license_key: 'gpl'

comment:
  <<: *default
  # selector: .comment-tinymce
  menubar: false

admin:
  <<: *default
  # selector: .admin-tinymce
  toolbar:
    - undo redo | blocks | bold italic | superscript | bullist numlist | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat
    - code | table | hr
    - image | link
  plugins:
    - image
    - link
    - table
    - lists
    - advlist
    - hr
    - code
  block_formats: 'Paragraph=p; Header 2=h2; Header 3=h3; Header 4=h4; Header 5=h5; Header 6=h6'
  images_upload_url: '/tinymce_assets' # for automatic_uploads
  images_upload_credentials: true # sends session information with the upload

  # This prevents tinymce from removing file host and using relative url
  relative_urls: false
  remove_script_host: false

  inline: true